import ElevenSquare.Tasks.T04.Alignment
import ElevenSquare.Tasks.T04.ReverseAlignment0
import ElevenSquare.Tasks.T04.ReverseAlignment1
import ElevenSquare.Tasks.T04.ReverseAlignment2
import ElevenSquare.Tasks.T04.ReverseAlignment3
import ElevenSquare.Tasks.T04.ReverseAlignment4
import ElevenSquare.Tasks.T04.ReverseAlignment5
import ElevenSquare.Tasks.T04.ReverseAlignment6
namespace ElevenSquare.Pending.T04Reverse
open GridDistance OverlayVertexChecks

theorem all_reverse_aligned :
    ArrayAligned ReverseRowFits recordedOverlayVertices recordedOverlayLabels :=
  T04Alignment.append_fourteen ReverseRowFits
    recordedOverlayVerticesChunk0 recordedOverlayVerticesChunk1 recordedOverlayVerticesChunk2 recordedOverlayVerticesChunk3 recordedOverlayVerticesChunk4 recordedOverlayVerticesChunk5 recordedOverlayVerticesChunk6 recordedOverlayVerticesChunk7 recordedOverlayVerticesChunk8 recordedOverlayVerticesChunk9 recordedOverlayVerticesChunk10 recordedOverlayVerticesChunk11 recordedOverlayVerticesChunk12 recordedOverlayVerticesChunk13
    recordedOverlayLabelsChunk0 recordedOverlayLabelsChunk1 recordedOverlayLabelsChunk2 recordedOverlayLabelsChunk3 recordedOverlayLabelsChunk4 recordedOverlayLabelsChunk5 recordedOverlayLabelsChunk6
    reverse_aligned0 reverse_aligned1 reverse_aligned2 reverse_aligned3 reverse_aligned4 reverse_aligned5 reverse_aligned6

#print axioms all_reverse_aligned


end ElevenSquare.Pending.T04Reverse
