import ElevenSquare.Pending.S07_GridLookupSupport
namespace ElevenSquare.Pending.GridDistance

theorem grid_lookup0 : gridArray[0]! = gridRow0 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 0 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 0 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 0 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 0 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 0 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 0 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 0 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 0 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 0 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 0 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 0 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 0 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 0 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup1 : gridArray[1]! = gridRow1 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 1 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 1 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 1 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 1 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 1 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 1 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 1 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 1 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 1 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 1 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 1 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 1 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 1 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup2 : gridArray[2]! = gridRow2 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 2 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 2 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 2 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 2 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 2 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 2 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 2 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 2 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 2 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 2 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 2 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 2 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 2 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup3 : gridArray[3]! = gridRow3 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 3 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 3 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 3 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 3 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 3 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 3 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 3 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 3 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 3 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 3 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 3 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 3 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 3 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup4 : gridArray[4]! = gridRow4 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 4 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 4 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 4 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 4 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 4 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 4 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 4 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 4 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 4 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 4 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 4 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 4 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 4 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup5 : gridArray[5]! = gridRow5 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 5 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 5 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 5 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 5 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 5 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 5 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 5 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 5 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 5 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 5 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 5 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 5 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 5 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup6 : gridArray[6]! = gridRow6 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 6 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 6 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 6 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 6 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 6 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 6 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 6 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 6 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 6 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 6 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 6 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 6 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 6 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup7 : gridArray[7]! = gridRow7 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 7 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 7 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 7 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 7 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 7 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 7 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 7 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 7 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 7 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 7 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 7 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 7 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 7 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup8 : gridArray[8]! = gridRow8 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 8 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 8 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 8 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 8 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 8 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 8 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 8 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 8 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 8 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 8 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 8 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 8 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 8 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup9 : gridArray[9]! = gridRow9 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 9 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 9 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 9 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 9 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 9 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 9 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 9 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 9 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 9 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 9 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 9 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 9 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 9 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup10 : gridArray[10]! = gridRow10 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 10 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 10 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 10 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 10 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 10 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 10 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 10 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 10 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 10 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 10 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 10 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 10 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 10 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup11 : gridArray[11]! = gridRow11 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 11 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 11 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 11 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 11 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 11 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 11 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 11 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 11 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 11 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 11 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 11 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 11 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 11 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup12 : gridArray[12]! = gridRow12 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 12 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 12 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 12 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 12 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 12 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 12 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 12 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 12 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 12 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 12 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 12 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 12 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 12 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup13 : gridArray[13]! = gridRow13 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 13 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 13 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 13 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 13 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 13 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 13 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 13 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 13 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 13 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 13 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 13 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 13 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 13 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup14 : gridArray[14]! = gridRow14 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 14 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 14 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 14 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 14 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 14 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 14 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 14 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 14 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 14 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 14 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 14 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 14 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 14 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

theorem grid_lookup15 : gridArray[15]! = gridRow15 := by
  rw [grid_array_eq_prefix]
  rw [gridPrefix13, lookup_left gridPrefix12 gridChunk13 15 (by rw [grid_prefix_size12]; decide)]
  rw [gridPrefix12, lookup_left gridPrefix11 gridChunk12 15 (by rw [grid_prefix_size11]; decide)]
  rw [gridPrefix11, lookup_left gridPrefix10 gridChunk11 15 (by rw [grid_prefix_size10]; decide)]
  rw [gridPrefix10, lookup_left gridPrefix9 gridChunk10 15 (by rw [grid_prefix_size9]; decide)]
  rw [gridPrefix9, lookup_left gridPrefix8 gridChunk9 15 (by rw [grid_prefix_size8]; decide)]
  rw [gridPrefix8, lookup_left gridPrefix7 gridChunk8 15 (by rw [grid_prefix_size7]; decide)]
  rw [gridPrefix7, lookup_left gridPrefix6 gridChunk7 15 (by rw [grid_prefix_size6]; decide)]
  rw [gridPrefix6, lookup_left gridPrefix5 gridChunk6 15 (by rw [grid_prefix_size5]; decide)]
  rw [gridPrefix5, lookup_left gridPrefix4 gridChunk5 15 (by rw [grid_prefix_size4]; decide)]
  rw [gridPrefix4, lookup_left gridPrefix3 gridChunk4 15 (by rw [grid_prefix_size3]; decide)]
  rw [gridPrefix3, lookup_left gridPrefix2 gridChunk3 15 (by rw [grid_prefix_size2]; decide)]
  rw [gridPrefix2, lookup_left gridPrefix1 gridChunk2 15 (by rw [grid_prefix_size1]; decide)]
  rw [gridPrefix1, lookup_left gridPrefix0 gridChunk1 15 (by rw [grid_prefix_size0]; decide)]
  rw [gridPrefix0]
  rfl

end ElevenSquare.Pending.GridDistance
#print axioms ElevenSquare.Pending.GridDistance.grid_lookup0
